import Link from 'next/link';
import "./globals.css";
import { Control } from './Control';

export const metadata = {
  title: "Next Practice",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await fetch(`http://localhost:9999/topics`, {
    cache: 'no-store'
  });
  const topics = await response.json();

  return (
    <html lang="en">
      <body>
        <div>
          <h1><Link href="/">WEB</Link></h1>
          <ol>
            {
              topics.map((topic) =>
                <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
              )
            }
          </ol>
          {children}
          <Control />
        </div>
      </body>
    </html>
  );
}


